baseurl = "https://rannathesleepbringer.github.io/aratestsite.github.io"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "docs"
title = "Antietam Radio"
canonifyurls  = true
relativeURLs = true

DefaultContentLanguage = "en"
theme = "hugo-theme-w3css-basic"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Antietam Radio Assn"
  logo = "img/avatar-icon2.png"
#removed the favicon line and added the section below steven
#  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  mainSections = ["post","posts"]
  readingTime = true
  wordCount = true
  useHLJS = false
# socialShare = true
# delayDisqus = true
# showRelatedPosts = true
  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"


#section added by steven
[params.favicon]
  # you may want to use https://realfavicongenerator.net to generate your files
  # used in layouts/partials/head.favicon.html
  # relURL is applied to path
  enable                 = false
  path                   = "img/favicon.ico"
  version                = "0.1.0"
  maskIcon               = "#5bbad5"
  msapplicationTileColor = "#da532c"
  themeColor             = "#ffffff"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Antietam Radio Association"
  email = "admin@w3cwc.com"
  #facebook = "username"
  #gitlab = "username"
  #github = "username"
  twitter = "@w3cwc"


#[[menu.main]]
#    name = "About"
#    url = "page/about/"
#    weight = 1

[[menu.main]]
  weight = 1
  name   = "Home"
  url    = "/index.html"
  pre    = "fas fa-home"

[[menu.main]]
    name = "Contact"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/contact"
    weight = 2

[[menu.main]]
    identifier = "activities"
    name = "https://rannathesleepbringer.github.io/aratestsite.github.io/Activities"
    weight = 3

[[menu.main]]
    parent = "activities"
    name = "Event Calendar"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/event-calendar"
    weight = 4

#
#[[menu.main]]
#    parent = "activities"
#    name = "Hamfest"
#    url = "/hamfest/"
#    weight = 1
#

[[menu.main]]
    parent = "activities"
    name = "Monthly Breakfast"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/breakfast"
    weight = 5

[[menu.main]]
    parent = "activities"
    name = "HPM Special Event"
    url = "post/2021-08-08-hpm/"
    weight = 6

[[menu.main]]
    parent = "activities"
    name = "ARRL Field Day"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/field-day"
    weight = 7

[[menu.main]]
    identifier = "info"
    name = "https://rannathesleepbringer.github.io/aratestsite.github.io/Club Info"
    weight = 2

[[menu.main]]
    parent = "info"
    name = "Get Your License!"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/testing"

[[menu.main]]
    parent = "info"
    name = "Join us!"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/membership"
    weight = 1

    [[menu.main]]
    parent = "info"
    name = "Contact Us!"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/contact"
    weight = 1

[[menu.main]]
    parent = "info"
    name = "ARA Bylaws"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/bylaws"
    weight = 2

[[menu.main]]
    parent = "info"
    name = "ARA Meetings"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/meeting-info"
    weight = 5

[[menu.main]]
    parent = "info"
    name = "Life Members"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/life-members"
    weight = 4

[[menu.main]]
    parent = "info"
    name = "ARA Officers"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/officers"
    weight = 6

[[menu.main]]
    parent = "info"
    name = "Nets & Repeaters"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/nets-repeaters"
    weight = 7

[[menu.main]]
    identifier = "resources"
    name = "https://rannathesleepbringer.github.io/aratestsite.github.io/Resources"
    weight = 3

[[menu.main]]
    parent = "resources"
    name = "Study Options"
    url = "post/2021-04-05-study-guides"

[[menu.main]]
    parent = "resources"
    name = "Presentations"
    url = "https://rannathesleepbringer.github.io/aratestsite.github.io/presentations"

[[menu.topbar]]
  weight   = 5
  name     = "Search"
  url      = "/search"
  pre      = "fas fa-search"
