# ##################################################
# theme-defined params

  # meta data
  # ##############################

  # used in layouts/partials/head.meta.html
  authorName                        = "Antietam Radio Association"
  defaultKeywords                   = ["HAM", "Radio"]
  defaultDescription                = "Antietam Radio Assnc"

  # multiple lines in toml
  # https://github.com/toml-lang/toml#user-content-string

  # used in layouts/partials/footer.html
  # uses markdownify
  aboutUs   = '''

General Email:
admin@w3cwc.com
This is a monitored email inbox, though it may take a few days to receive a reply, since the the one monitoring the box may not be the one who can best answer your question.

Mailing Address:

Antietam Radio Association
Post Office Box 52
Hagerstown, MD 21741-0052


              '''

  address   = '''
Antietam Radio Association

Post Office Box 52

Hagerstown, MD 21741-0052

              '''

  # used in layouts/partials/footer.bottom.html
  bottomLeft  = "Copyright (c) 2022, *Stuff"
  bottomRight = 'created with [Hugo](https://gohugo.io) '


[jumbotrons]
  enable   = true

[photocards]
  enable        = true

[features]
  enable   = false

[recentPosts]
  footerNumOfPosts = 5
  enableFront    = false
  enableFooter   = true
  title    = "From our Blog"
  subtitle = '''
Pellentesque habitant morbi tristique senectus et netus et malesuada
fames ac.
             '''

[seeMore]
  enable    = false
  linkText  = "consectetuer adipiscing"
  subtitle  = '''
Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper
suscipit lobortis nisl ut aliquip ex ea commodo consequat.
              '''

[testimonials]
  enable   = false
  title    = "Testimonials"
  subtitle = '''
Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
labore et dolore magna aliquyam erat, sed diam voluptua.
             '''

[clients]
  enable        = false
  title         = "Our Members"
  subtitle      = '''
---------------------------------------------
              ### 2022-2023
              Position|Member|Call
              ---|---|---
              President|Brian Umbrell|W3PDW
              Vice Pres|Herm Niedzielski|K2AVA
              Treasurer|Tim Keener|N3VGS
              Secretary|Bill Collins|K3WJC
              Activities|Steve Struharik|WA8EIH
              Director|Cliff Engle|W3KKO
              Director|Pat Goodrich|KB3YSV
              Director|Robbie McFerren|KB3PXR
----------------------------------------------
             '''

[blog]
  title    = "Blog"
  icon     = "fas fa-rss"
  subtitle = '''
ultricies eget, tempor sit amet, ante
             '''

[googleApiFonts.family]
  tagsText        = [ "html", "body", "time" ]
  tagsHeading     = [ "h1", "h2", "h3", "h4", "h5", "h6" ]
  tagsMono        = [ "pre", "code", "kbd", "samp", "data" ]

  # these parameter sections must exist, the others are optional
  fallbackText    = "html"
  fallbackHeading = "h1"
  fallbackMono    = "pre"

[googleApiFonts.family.html]
  sans-serif = "Ubuntu"

[googleApiFonts.family.time]
  cursive    = "Creepster"

[googleApiFonts.family.h1]
  sans-serif = "Signika"

[googleApiFonts.family.pre]
  monospace  = "Ubuntu Mono"


[options]
  jsHistoryNav        = true
  jsHistoryNavForward = false
  showNavUp           = true
  showNavBreadcrump   = true
  navBreadcrumpTitle  = true
  navBreadcrumpHome   = false
